export const tips = [
    "Carbs are your best fuel source, so try a light meal 1–2 hrs before training.",
    "Protein within an hour after your workout helps kick off muscle repair.",
    "A 5–10 minute dynamic warm-up primes your joints and lowers injury risk.",
    "Progressive overload beats intensity spikes, so add small, steady increases over time.",
    "Sleep is when most of your recovery actually happens, aim for 7–9 hours every night.",
    "Dehydration shows up as fatigue before it shows up as thirst, so sip water throughout the day, not just during workouts.",
    "Sore isn't the same as strong. A drop in soreness doesn't mean you've stopped progressing.",
    "Rest days aren't wasted days. Muscle rebuilds during recovery, not during the set.",
    "Form breakdown is your body's signal to lower the weight, not push through.",
    "Compound lifts (squats, deadlifts, presses) give you more return per minute than isolation work.",
    "Track your lifts: \"I think I did more last time\" is a lot less useful than a number.",
    "A missed workout doesn't erase progress, but a missed week of consistency might.",
    "Breathe out on the exertion phase of a lift, not during the hold.",
    "Stretching cold muscles is riskier than stretching warm ones, so save static stretches for after training.",
    "Grip strength fatigues before the target muscle does on some lifts, so straps aren't cheating, they're strategy.",
    "Two steps forward, one step back is still forward. Don't judge a program by one bad session.",
    "Consistency at 70% effort beats sporadic bursts at 100%.",
    "A tight hip flexor can masquerade as a weak glute, which is why mobility work isn't optional.",
    "Eating enough matters as much as eating \"clean\": under-fueling stalls recovery and strength gains alike.",
    "The best workout program is the one you'll actually keep doing.",
    "Warm up the exact movement pattern you're about to load, not just a generic jog.",
    "Muscle confusion is a myth. Muscles respond to progressive tension, not novelty.",
    "A spotter or safety bars matter more as the weight gets heavier, not less.",
    "Cardio and strength training aren't rivals. They support different adaptations.",
    "Your last rep should be hard, not sloppy. Technique still counts at failure.",
    "Caffeine timed 30–60 minutes before training can measurably boost performance.",
    "A workout log is only useful if you actually look back at it.",
    "Delayed-onset soreness usually peaks 24–72 hrs after training, not immediately.",
    "Small plates add up, so don't forget to log the increments when you round up.",
    "If a lift hurts (sharp, joint-level) versus burns (muscular fatigue), those are different signals, so don't push through the first one.",
    "Tracking bodyweight day-to-day is noisy. Trends over weeks matter more than any single number.",
    "A goal without a deadline is just a wish. Set a target date for your next milestone.",
    "Fiber and protein both help you feel full, making them your best tools against mindless snacking.",
    "Training to technical failure isn't required every set to build muscle.",
    "Your warm-up sets should feel easy, so save the effort for your working sets.",
    "Recovery nutrition matters most after your hardest sessions, not your easiest ones.",
    "A longer rest between heavy sets (2–3 min) lets you lift more total volume than rushing.",
    "Flexibility and mobility aren't the same thing. Mobility is control through a range of motion, not just reach.",
    "The scale doesn't know the difference between muscle and fat, so don't let it be your only metric.",
    "Alcohol the night before a workout measurably hurts next-day performance and recovery.",
    "Habits stick better when they're attached to an existing routine, so pair workouts with something you already do daily.",
    "A strong core isn't just abs. It's the bracing that protects your spine under load.",
    "Improvement isn't always visible week to week. That's what the log is for.",
    "Cooling down doesn't undo a hard session, but a short walk helps you transition out of it instead of stopping cold.",
];

export function getTipOfTheDay(date = new Date()) {
    const startOfYear = new Date(date.getFullYear(), 0, 0);
    const dayOfYear = Math.floor((date - startOfYear) / 86400000);
    return tips[dayOfYear % tips.length];
}
